package com.campusconnect.campusconnect.controller;
import com.campusconnect.campusconnect.entity.*; import com.campusconnect.campusconnect.repository.*; import org.springframework.web.bind.annotation.*; import jakarta.servlet.http.HttpSession; import java.util.*;
@RestController @RequestMapping("/api/marketplace")
public class MarketplaceController {
 final ListingRepository listings; final UserRepository users; final NotificationRepository notifications;
 public MarketplaceController(ListingRepository l,UserRepository u,NotificationRepository n){listings=l;users=u;notifications=n;}
 private Long me(HttpSession s){Object x=s.getAttribute("userId");if(x==null)throw new IllegalArgumentException("Log in first");return ((Number)x).longValue();}
 private Map<String,Object> dto(Listing x){Map<String,Object> m=new LinkedHashMap<>();m.put("id",x.getId());m.put("title",x.getTitle());m.put("description",x.getDescription());m.put("price",x.getPrice());m.put("category",x.getCategory()==null?"":x.getCategory());m.put("location",x.getLocation()==null?"":x.getLocation());m.put("imageUrl",x.getImageUrl()==null?"":x.getImageUrl());m.put("sold",x.isSold());m.put("sellerId",x.getSeller().getId());m.put("sellerUsername",x.getSeller().getUsername());m.put("createdAt",x.getCreatedAt());return m;}
 @GetMapping public List<Map<String,Object>> all(@RequestParam(required=false) String category){List<Listing> xs=(category==null||category.isBlank()||category.equalsIgnoreCase("All"))?listings.findAllByOrderByCreatedAtDesc():listings.findByCategoryOrderByCreatedAtDesc(category);return xs.stream().map(this::dto).toList();}
 @PostMapping public Map<String,Object> create(@RequestBody Map<String,Object> b,HttpSession s){User u=users.findById(me(s)).orElseThrow();String title=String.valueOf(b.getOrDefault("title","")).trim();String desc=String.valueOf(b.getOrDefault("description","")).trim();if(title.isEmpty()||desc.isEmpty())throw new IllegalArgumentException("Title and description are required");Listing x=new Listing();x.setTitle(title);x.setDescription(desc);x.setPrice(Double.parseDouble(String.valueOf(b.getOrDefault("price","0"))));x.setCategory(String.valueOf(b.getOrDefault("category","Other")));x.setLocation(String.valueOf(b.getOrDefault("location","")));String imageUrl=String.valueOf(b.getOrDefault("imageUrl","")).trim();if(imageUrl.isBlank())throw new IllegalArgumentException("An item photo is required");x.setImageUrl(imageUrl);x.setSeller(u);return dto(listings.save(x));}
 @PostMapping("/{id}/sold") public Map<String,Object> sold(@PathVariable Long id,HttpSession s){Listing x=listings.findById(id).orElseThrow();if(!x.getSeller().getId().equals(me(s)))throw new IllegalArgumentException("Only the seller can mark this listing sold");x.setSold(true);return dto(listings.save(x));}
 @DeleteMapping("/{id}") public void delete(@PathVariable Long id,HttpSession s){Listing x=listings.findById(id).orElseThrow();if(!x.getSeller().getId().equals(me(s)))throw new IllegalArgumentException("Only the seller can delete this listing");listings.delete(x);}
}