# =========================
# Server
# =========================
server.port=${PORT:8080}

# =========================
# Aiven MySQL Database
# =======================
spring.datasource.url=mysql://avnadmin:AVNS_3iQY7HnujORV3vVmEPQ@campusconnect-db-dincedyden-d923.j.aivencloud.com:22306/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=${avnadmin}
spring.datasource.password=${1qa2ws3ed2005}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================
# Connection Pool
# =========================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# =========================
# JSON
# =========================
spring.jackson.serialization.fail-on-empty-beans=false

# =========================
# Time Zone
# =========================
spring.jackson.time-zone=Africa/Lusaka

# =========================
# File Uploads
# =========================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

# =========================
# Error Handling
# =========================
server.error.include-message=always
server.error.include-binding-errors=always
